In [22]:
import pandas as pd 
df = pd.read_csv("../data/sales_data.csv", na_values=["NONE"])
df

    order_id  customer_id     region  product    sales  quantity
0     1001.0            1     Dubaii    Phone     1200         2
1     1002.0            2      Dubai   Laptop     2500         1
2     1003.0            3    Sharjah    phone      900         1
3     1004.0            4  Abu Dhabi   Tablet     1800         2
4     1005.0            5        NaN   Laptop     3200         1
5     1006.0            6   Sharjah     Phone     1100         2
6     1007.0            7  Abu Dhabi   Laptop     2800         1
7        NaN            8      Dubai    Phone     1400         2
8     1009.0            9    Sharjah   TABLET     1600         1
9     1010.0           10      Dubai   Laptop     2700         1
10    1011.0            1      Dubai    Phone      NaN         2
11    1012.0            2      Dubai   Tablet     1900         1
12    1013.0            3    Sharjah   Laptop     2600         1
13    1014.0            4  Abu Dhabi    Phone     1500         2
14    1015.0            5      Dubai   Tablet  unknown         1
15    1016.0            6    Sharjah   Laptop     3000        -1
16    1017.0            7  Abu Dhabi    Phone     1700         2
17    1018.0            8      Dubai  Laptop     -2900         1
18    1019.0            9    Sharjah    Phone     1250         2
19    1020.0           10      Dubai   Tablet     2000         1

In [23]:
df.shape

(20, 6)

In [24]:
df.size

120

In [27]:
df.info

<bound method DataFrame.info of     order_id  customer_id     region  product    sales  quantity
0     1001.0            1     Dubaii    Phone     1200         2
1     1002.0            2      Dubai   Laptop     2500         1
2     1003.0            3    Sharjah    phone      900         1
3     1004.0            4  Abu Dhabi   Tablet     1800         2
4     1005.0            5        NaN   Laptop     3200         1
5     1006.0            6   Sharjah     Phone     1100         2
6     1007.0            7  Abu Dhabi   Laptop     2800         1
7        NaN            8      Dubai    Phone     1400         2
8     1009.0            9    Sharjah   TABLET     1600         1
9     1010.0           10      Dubai   Laptop     2700         1
10    1011.0            1      Dubai    Phone      NaN         2
11    1012.0            2      Dubai   Tablet     1900         1
12    1013.0            3    Sharjah   Laptop     2600         1
13    1014.0            4  Abu Dhabi    Phone     1500         2
14    1015.0            5      Dubai   Tablet  unknown         1
15    1016.0            6    Sharjah   Laptop     3000        -1
16    1017.0            7  Abu Dhabi    Phone     1700         2
17    1018.0            8      Dubai  Laptop     -2900         1
18    1019.0            9    Sharjah    Phone     1250         2
19    1020.0           10      Dubai   Tablet     2000         1>

In [28]:
df.isnull().sum()

order_id       1
customer_id    0
region         1
product        0
sales          1
quantity       0
dtype: int64

In [30]:
for col in df.columns:
    print("\n---", col, "---")
    print(df[col].unique())

--- order_id ---
[1001. 1002. 1003. 1004. 1005. 1006. 1007.   nan 1009. 1010. 1011. 1012.
 1013. 1014. 1015. 1016. 1017. 1018. 1019. 1020.]

--- customer_id ---
[ 1  2  3  4  5  6  7  8  9 10]

--- region ---
<StringArray>
['Dubaii', 'Dubai', 'Sharjah', 'Abu Dhabi', nan, 'Sharjah ']
Length: 6, dtype: str

--- product ---
<StringArray>
['Phone', 'Laptop', 'phone', 'Tablet', 'TABLET', 'Laptop ']
Length: 6, dtype: str

--- sales ---
<StringArray>
[   '1200',    '2500',     '900',    '1800',    '3200',    '1100',    '2800',
    '1400',    '1600',    '2700',       nan,    '1900',    '2600',    '1500',
 'unknown',    '3000',    '1700',   '-2900',    '1250',    '2000']
Length: 20, dtype: str

--- quantity ---
[ 2  1 -1]

In [34]:
df.describe(include="all")

           order_id  customer_id region product sales   quantity
count     19.000000    20.000000     19      20    19  20.000000
unique          NaN          NaN      5       6    19        NaN
top             NaN          NaN  Dubai   Phone  1200        NaN
freq            NaN          NaN      8       7     1        NaN
mean    1010.631579     5.500000    NaN     NaN   NaN   1.300000
std        6.048053     2.946898    NaN     NaN   NaN   0.732695
min     1001.000000     1.000000    NaN     NaN   NaN  -1.000000
25%     1005.500000     3.000000    NaN     NaN   NaN   1.000000
50%     1011.000000     5.500000    NaN     NaN   NaN   1.000000
75%     1015.500000     8.000000    NaN     NaN   NaN   2.000000
max     1020.000000    10.000000    NaN     NaN   NaN   2.000000

In [38]:
df[df.isnull().any(axis=1)]

    order_id  customer_id region product sales  quantity
4     1005.0            5    NaN  Laptop  3200         1
7        NaN            8  Dubai   Phone  1400         2
10    1011.0            1  Dubai   Phone   NaN         2

In [39]:
df["sales"].unique()

<StringArray>
[   '1200',    '2500',     '900',    '1800',    '3200',    '1100',    '2800',
    '1400',    '1600',    '2700',       nan,    '1900',    '2600',    '1500',
 'unknown',    '3000',    '1700',   '-2900',    '1250',    '2000']
Length: 20, dtype: str

In [47]:
df["sales"] = pd.to_numeric(df["sales"], errors="coerce")

In [49]:
df["sales"].isnull().sum()

np.int64(2)

In [51]:
df["region"] = df["region"].str.strip().str.title()
df["product"] = df["product"].str.strip().str.title()

In [56]:
df.describe()

          order_id  customer_id        sales   quantity
count    19.000000    20.000000    18.000000  20.000000
mean   1010.631579     5.500000  1680.555556   1.300000
std       6.048053     2.946898  1339.132609   0.732695
min    1001.000000     1.000000 -2900.000000  -1.000000
25%    1005.500000     3.000000  1287.500000   1.000000
50%    1011.000000     5.500000  1750.000000   1.000000
75%    1015.500000     8.000000  2575.000000   2.000000
max    1020.000000    10.000000  3200.000000   2.000000

In [55]:
df["region"] = df["region"].replace({"Dubaii": "Dubai"})

In [57]:
df[df["sales"] < 0]

    order_id  customer_id region product   sales  quantity
17    1018.0            8  Dubai  Laptop -2900.0         1

In [58]:
df[df["quantity"] < 0]

    order_id  customer_id   region product   sales  quantity
15    1016.0            6  Sharjah  Laptop  3000.0        -1

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     19 non-null     float64
 1   customer_id  20 non-null     int64
 2   region       19 non-null     str
 3   product      20 non-null     str
 4   sales        18 non-null     float64
 5   quantity     20 non-null     int64
dtypes: float64(2), int64(2), str(2)
memory usage: 1.1 KB

In [60]:
df.isnull().sum()

order_id       1
customer_id    0
region         1
product        0
sales          2
quantity       0
dtype: int64

In [61]:
df.duplicated().sum()

np.int64(0)

In [69]:
df["sales"] = df["sales"].fillna(df["sales"].median())
df["region"] = df["region"].fillna("unknown")

In [72]:

df["order_id"] = df["order_id"].fillna("unknown")

In [73]:
df.isnull().sum()

order_id       0
customer_id    0
region         0
product        0
sales          0
quantity       0
dtype: int64

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     20 non-null     object
 1   customer_id  20 non-null     int64
 2   region       20 non-null     str
 3   product      20 non-null     str
 4   sales        20 non-null     float64
 5   quantity     20 non-null     int64
dtypes: float64(1), int64(2), object(1), str(2)
memory usage: 1.1+ KB

In [81]:
sales_by_region = (df.groupby("region")["sales"].sum().sort_values(ascending=False))
sales_by_region

region
Dubai        12300.0
Sharjah      10450.0
Abu Dhabi     7800.0
unknown       3200.0
Name: sales, dtype: float64

In [82]:
sales_by_product = (df.groupby("product")["sales"].sum().sort_values(ascending=False))

In [83]:
sales_by_product

product
Laptop    13900.0
Phone     10800.0
Tablet     9050.0
Name: sales, dtype: float64

In [84]:
df["sales"].mean()

np.float64(1687.5)

In [85]:
df.groupby(["region", "product"])["sales"].sum()

region     product
Abu Dhabi  Laptop     2800.0
           Phone      3200.0
           Tablet     1800.0
Dubai      Laptop     2300.0
           Phone      4350.0
           Tablet     5650.0
Sharjah    Laptop     5600.0
           Phone      3250.0
           Tablet     1600.0
unknown    Laptop     3200.0
Name: sales, dtype: float64

In [87]:
pivot = pd.pivot_table(df, values="sales", index="region", columns="product", aggfunc="sum", fill_value=0)

In [88]:
pivot

product    Laptop   Phone  Tablet
region
Abu Dhabi  2800.0  3200.0  1800.0
Dubai      2300.0  4350.0  5650.0
Sharjah    5600.0  3250.0  1600.0
unknown    3200.0     0.0     0.0

In [89]:
top_region = sales_by_region.idxmax()
top_region_sales = sales_by_region.max()

print("Top region:", top_region)
print("Total sales:", top_region_sales)

Top region: Dubai
Total sales: 12300.0

In [90]:
top_product = sales_by_product.idxmax()
top_product_sales = sales_by_product.max()

print("Top product:", top_product)
print("Total sales:", top_product_sales)

Top product: Laptop
Total sales: 13900.0

In [91]:
total_sales = df["sales"].sum()

print("Total sales:", total_sales)

Total sales: 33750.0